
name : '📦 𝗣𝗮𝗰𝗸𝗮𝗴𝗲 - 𝗥𝗲𝗺𝗼𝘃𝗮𝗹'

description : 'Remove an existing Python package.'
title : '‹Package›'

labels : [ '📦 𝗣𝗮𝗰𝗸𝗮𝗴𝗲' , '-' ]

body:

    -   type : 'markdown'

        attributes:
            value : '<!-- Spacer -->'

    -   type : 'input'
        id : 'Removed'

        attributes :

            description : 'Handle of the [PyPI](https://pypi.org/) package.'
            placeholder : 'package-a'
            label : '📦 𝗣𝗮𝗰𝗸𝗮𝗴𝗲'

        validations:
            required : true

    -   type : 'markdown'

        attributes:
            value : '<!-- Spacer -->'

    -   type : 'textarea'
        id : 'Reason'

        attributes :

            description : 'Describe why you are requesting this change.'
            placeholder : 'This package is malicious, breaking, unmaintained, ..'
            render : 'txt'
            label : '📑 𝗥𝗲𝗮𝘀𝗼𝗻'

        validations:
            required : true