
name : '📦 𝗣𝗮𝗰𝗸𝗮𝗴𝗲 - 𝗥𝗲𝗽𝗹𝗮𝗰𝗲𝗺𝗲𝗻𝘁'

description : 'Replace one Python package with another.'
title : '‹Package›'

labels : [ '📦 𝗣𝗮𝗰𝗸𝗮𝗴𝗲' , '±' ]

body:

    -   type : 'markdown'

        attributes:
            value : '<!-- Spacer -->'

    -   type : 'input'
        id : 'Removed'

        attributes :

            description : 'Handle of the [PyPI](https://pypi.org/) package to be replaced.'
            placeholder : 'package-a'
            label : '📦 𝗣𝗮𝗰𝗸𝗮𝗴𝗲 ( Removed )'

        validations:
            required : true

    -   type : 'input'
        id : 'Added'

        attributes :

            description : 'Handle of the [PyPI](https://pypi.org/) package to replace it with.'
            placeholder : 'package-b'
            label : '📦 𝗣𝗮𝗰𝗸𝗮𝗴𝗲 ( Added )'

        validations:
            required : true

    -   type : 'markdown'

        attributes:
            value : '<!-- Spacer -->'

    -   type : 'textarea'
        id : 'Reason'

        attributes :

            description : 'Describe why you are requesting this change.'
            placeholder : 'The existing package was replaced as of Python `3.11`.'
            render : 'txt'
            label : '📑 𝗥𝗲𝗮𝘀𝗼𝗻'

        validations:
            required : true
